### ISSUE TITLE
As generated PKCE verifier

### ISSUE THREAD

**Issue by tlodderstedt** [oauthstuff/draft-oauth-par#37]
In case of PAR, the AS could generate the PKCE verifier and return it in the PAR response.All it needs is another code_challenge_method. e.g. "as_generated".

I think this would make the life of client developers easier. The don't need to generate the random value and corresponding hash. They just use the code_verifier as provided by the AS in the token request.

Observation: this is similar to the device flow's device code. 

Thoughts?

**Comment by danielfett** [comment]
From a security perspective, the advantage is that developers of clients have less options for errors in implementations (although generating a PKCE challenge and verifier is not complicated). 

We are weakening the protocol, however: PKCE binds the code to a sender (the client), and the only entitity knowing the PKCE verifier is the client itself. **As a general concept, this is a good design choice.** If the server generates the PKCE challenge/verifier, the server (or just the PAR endpoint) might be under the control of an attacker and generate a verifier that serves a specific purpose. This weakens the protection against code injection that PKCE provides when combined with PAR:

Let's assume that an attacker observes code and code_verifier (e.g., because he has compromised a token endpoint or through a mix-up attack). The attacker cannot exchange the code himself because he does not know the client's credentials, e.g., because asymmetric methods are used. With current PKCE S256, the attacker could, however, do a code injection attack by starting a new flow (in his browser) between the client and the AS. The attacker can modify the authz request code_challenge to be the hash of the observed code_verifier. In the authz response, the attacker replaces the code sent by the AS with the code captured earlier. The client will now use his client credentials to exchange the code for a token, which the attacker (through the AS) can make use of.

PAR prevents this attack: Since the client select code_challenge, and PAR provides integrity for the authz request, the attacker will not be able to start a second flow with the same client and a matching code_challenge.

If the AS can issue the code_verifier, the attacker could set up a malicious AS, but advertise the honest AS's token endpoint as the matching token endpoint. In this case, the attacker would be able to calculate a matching code_verifier from the observed code_verifier, issue it to the client, and the code injection would succeed.

**There are a lot of assumptions needed to pull this attack off, but I do not have a good feeling here. Maybe we can come up with an easier attack that is enabled by this change. If not, we have to consider the trade off between a slightly increased attack surface and slightly more comfortable and less error-prone client implementations.**

**Comment by b---c** [comment]
While the happy path might be marginally simpler for a client developer it would bring with it new complexities in other areas. What takes precedence or is allowed, for example, when a client sends a code_challenge in the pushed authz req? The spec would have to account for such cases, which will muddy up the document. I don't think it's worth it.

**Comment by panva** [comment]
I agree with Brian here, plus i don't feel like a new PKCE method definition belongs to PAR specification altogether.

**Comment by tlodderstedt** [comment]
could go into another spec - this also makes sense since it could be used with any backchannel based method, like CIBA

**Comment by b---c** [comment]
I'm not sure I see the parallel or applicability with device code and CIBA. But that's a bit of a tangent. 

I'll just reiterate that I do think PAR shouldn't try and do anything new w/ PKCE.

**Comment by leastprivilege** [comment]
> I'll just reiterate that I do think PAR shouldn't try and do anything new w/ PKCE.

Agreed. I like the idea of the code verifier being a client generated per-request secret. And RNGs/SHA256 are pretty much everywhere these days.

**Comment by tlodderstedt** [comment]
thanks guys, that sounds like a conclusion.
