### ISSUE TITLE
bad internal links in section 2.3

### ISSUE THREAD

**Issue by jogu** [oauthstuff/draft-oauth-par#62]
Very minor, but https://tools.ietf.org/html/draft-ietf-oauth-par-03#section-2.3 has the following html:

```
If the authorization server sets an error code, it SHOULD be one of
   the defined codes for the token endpoint in <a href="#section-5.2">Section 5.2</a> or for the
   authorization endpoint in Sections <a href="#section-4.1.2.1">4.1.2.1</a> and <a href="#section-4.2.2.1">4.2.2.1</a> of [<a href="./rfc6749" title="&quot;The OAuth 2.0 Authorization Framework&quot;">RFC6749</a>],
```

the `4.1.2.1` text is linked to the non-existent 4.1.2.1 section of PAR rather than to rfc6749.

**Comment by jogu** [comment]
The bad links don't appear in https://www.ietf.org/id/draft-ietf-oauth-par-03.html which seems weird. I have no idea how any of this stuff works, maybe it's a oddity in the IETF tooling...

**Comment by b---c** [comment]
It is a tooling thing. The https://tools.ietf.org/html/draft-ietf-oauth-par-03 style of document is HTML produced from the plain text version (htmlized as they call it) of the document and this happens after submitting the I-D for publication. It has some heuristics for how it builds links but is kinda finicky and, if the text isn't just right, often results in these erroneous self referential links. The problem is certinally not unique to this draft. The htmlize tool can be run locally to check this stuff but is extra work that typically doesn't happen.  The https://www.ietf.org/id/draft-ietf-oauth-par-03.html style document is the "new" HTML style, which is produced directly from the XML source so is more predictable in how it deals with links and references. 

I'm going to rework some of the text in that area anyway and will try and rephrase that bit in a way that will hopefully play nicer with the htmlize tool. But I'm not going to lose sleep over it.
